after_success:
- coveralls
before_install:
- pip install coveralls
dist: xenial
install:
- pip install -r tests/requirements.txt
language: python
matrix:
  include:
    - python: 3.7
      install: pip install --pre -r tests/requirements.txt
      env:
        - PRE=True  # not used, just to make it visible
notifications:
  email:
    on_failure: change
    on_success: change
python:
- 2.7
- 3.4
- 3.5
- 3.6
- 3.7
script: make test
