after_success:
- coveralls
before_install:
- pip install coveralls
install:
- pip install -r test_requirements.txt
language: python
notifications:
  email:
    on_failure: change
    on_success: change
python:
- 2.7
- 3.3
- 3.4
- 3.5
script: make test
